{% set version = "0.9.8" %}

package:
  name: hyperion
  version: {{version}}

source:
  fn: Hyperion-{{version}}.tar.gz
  url: https://pypi.io/packages/source/h/hyperion/Hyperion-{{version}}.tar.gz
  md5: 970ebfa8b65c4a181fcdd788ee71dd38

build:
  number: 1
  script: python setup.py install
  skip: True  # [win]

requirements:

  build:
    - python
    - setuptools
    - numpy x.x

  run:
    - hyperion-fortran 0.9.8
    - python
    - numpy x.x
    - matplotlib
    - h5py
    - astropy
    - yt <3.3

test:
  imports:
    - hyperion
    - hyperion.util.interpolate
  commands:
    - hyperion --help

about:
  home: https://github.com/hyperion-rt/hyperion
  license: BSD 2-Clause
  summary: Hyperion Radiation Transfer Code

extra:
  recipe-maintainers:
    - astrofrog
