travis:
  secure:
    BINSTAR_TOKEN: VxewUxAzVcEkdQSnfWbepuVNGH3PWQUY19O8uyySZD5PwIqNYjWFoKjYLzsjuJ2kV6njHwj6elNJ7d7YFExgNBWKfkk+lJEnPS1qSTvUhPBotzcubYwoBRObrJDoV6EyIGbvtrysHFuHLJyFZ/c97DrSXR8uO7qEsb+mE78t2GYBtAmGAQSBKFIFw3sRyMGuE55NqBd0nn/83TUg9Ao0hMImqXPkZ0/m/exB9uuvbYker2c0VQLyTlutaNEi5h+WTDQIF4vlOvmtRVYWB0dGmSyaAH6u4ItAN+wz6e7LN1hjEtfvUCaskjXyf2AlEJyFHSDEV8T92pAgfPyP7wsRmxahho9yZPWVkf8hT9iFVDhELDHeb9l08aVRv+WoryV8/PBVjsHfABb3y1+n7G9fBtOLhfZyPcbnJ2LO6BldTRDitbJ/dSME+XLVfCRkO2WzPFJf6r3/1CfZ6wvUUfJ9CKvy3OxuARtxm+PmxHFs96U4YSb+PDaW4GPk4WSJmTpeBuZ0APcymTBpn7BbHhRy3jNUcQa+ul0HE889DdJKONMYqeVdbTRr9QNF3K+ZH5yG7iRmAwZ2i0o8NczFI+/gYqKiv8zRQdzDeJ3kT0aOKtokHfSiSVkrQkTvSwGCch1k8z0nv9aVCWlJEr0nKqwbz7k+zv/qp+o7Xn+PDXAPfzo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
